./target/release/examples/trophic_run --seed 0 --ticks 50000 --jsonl /tmp/theory_arms/A_s0.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s0.out 2>&1
./target/release/examples/trophic_run --seed 0 --ticks 50000 --jsonl /tmp/theory_arms/F_s0.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s0.out 2>&1
./target/release/examples/trophic_run --seed 0 --ticks 50000 --jsonl /tmp/theory_arms/AF_s0.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s0.out 2>&1
./target/release/examples/trophic_run --seed 1 --ticks 50000 --jsonl /tmp/theory_arms/A_s1.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s1.out 2>&1
./target/release/examples/trophic_run --seed 1 --ticks 50000 --jsonl /tmp/theory_arms/F_s1.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s1.out 2>&1
./target/release/examples/trophic_run --seed 1 --ticks 50000 --jsonl /tmp/theory_arms/AF_s1.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s1.out 2>&1
./target/release/examples/trophic_run --seed 2 --ticks 50000 --jsonl /tmp/theory_arms/A_s2.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s2.out 2>&1
./target/release/examples/trophic_run --seed 2 --ticks 50000 --jsonl /tmp/theory_arms/F_s2.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s2.out 2>&1
./target/release/examples/trophic_run --seed 2 --ticks 50000 --jsonl /tmp/theory_arms/AF_s2.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s2.out 2>&1
./target/release/examples/trophic_run --seed 3 --ticks 50000 --jsonl /tmp/theory_arms/A_s3.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s3.out 2>&1
./target/release/examples/trophic_run --seed 3 --ticks 50000 --jsonl /tmp/theory_arms/F_s3.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s3.out 2>&1
./target/release/examples/trophic_run --seed 3 --ticks 50000 --jsonl /tmp/theory_arms/AF_s3.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s3.out 2>&1
./target/release/examples/trophic_run --seed 4 --ticks 50000 --jsonl /tmp/theory_arms/A_s4.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s4.out 2>&1
./target/release/examples/trophic_run --seed 4 --ticks 50000 --jsonl /tmp/theory_arms/F_s4.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s4.out 2>&1
./target/release/examples/trophic_run --seed 4 --ticks 50000 --jsonl /tmp/theory_arms/AF_s4.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s4.out 2>&1
./target/release/examples/trophic_run --seed 5 --ticks 50000 --jsonl /tmp/theory_arms/A_s5.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s5.out 2>&1
./target/release/examples/trophic_run --seed 5 --ticks 50000 --jsonl /tmp/theory_arms/F_s5.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s5.out 2>&1
./target/release/examples/trophic_run --seed 5 --ticks 50000 --jsonl /tmp/theory_arms/AF_s5.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s5.out 2>&1
./target/release/examples/trophic_run --seed 6 --ticks 50000 --jsonl /tmp/theory_arms/A_s6.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s6.out 2>&1
./target/release/examples/trophic_run --seed 6 --ticks 50000 --jsonl /tmp/theory_arms/F_s6.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s6.out 2>&1
./target/release/examples/trophic_run --seed 6 --ticks 50000 --jsonl /tmp/theory_arms/AF_s6.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s6.out 2>&1
./target/release/examples/trophic_run --seed 7 --ticks 50000 --jsonl /tmp/theory_arms/A_s7.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s7.out 2>&1
./target/release/examples/trophic_run --seed 7 --ticks 50000 --jsonl /tmp/theory_arms/F_s7.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s7.out 2>&1
./target/release/examples/trophic_run --seed 7 --ticks 50000 --jsonl /tmp/theory_arms/AF_s7.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s7.out 2>&1
./target/release/examples/trophic_run --seed 8 --ticks 50000 --jsonl /tmp/theory_arms/A_s8.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s8.out 2>&1
./target/release/examples/trophic_run --seed 8 --ticks 50000 --jsonl /tmp/theory_arms/F_s8.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s8.out 2>&1
./target/release/examples/trophic_run --seed 8 --ticks 50000 --jsonl /tmp/theory_arms/AF_s8.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s8.out 2>&1
./target/release/examples/trophic_run --seed 9 --ticks 50000 --jsonl /tmp/theory_arms/A_s9.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s9.out 2>&1
./target/release/examples/trophic_run --seed 9 --ticks 50000 --jsonl /tmp/theory_arms/F_s9.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s9.out 2>&1
./target/release/examples/trophic_run --seed 9 --ticks 50000 --jsonl /tmp/theory_arms/AF_s9.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s9.out 2>&1
./target/release/examples/trophic_run --seed 10 --ticks 50000 --jsonl /tmp/theory_arms/A_s10.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s10.out 2>&1
./target/release/examples/trophic_run --seed 10 --ticks 50000 --jsonl /tmp/theory_arms/F_s10.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s10.out 2>&1
./target/release/examples/trophic_run --seed 10 --ticks 50000 --jsonl /tmp/theory_arms/AF_s10.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s10.out 2>&1
./target/release/examples/trophic_run --seed 11 --ticks 50000 --jsonl /tmp/theory_arms/A_s11.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s11.out 2>&1
./target/release/examples/trophic_run --seed 11 --ticks 50000 --jsonl /tmp/theory_arms/F_s11.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s11.out 2>&1
./target/release/examples/trophic_run --seed 11 --ticks 50000 --jsonl /tmp/theory_arms/AF_s11.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s11.out 2>&1
./target/release/examples/trophic_run --seed 12 --ticks 50000 --jsonl /tmp/theory_arms/A_s12.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s12.out 2>&1
./target/release/examples/trophic_run --seed 12 --ticks 50000 --jsonl /tmp/theory_arms/F_s12.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s12.out 2>&1
./target/release/examples/trophic_run --seed 12 --ticks 50000 --jsonl /tmp/theory_arms/AF_s12.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s12.out 2>&1
./target/release/examples/trophic_run --seed 13 --ticks 50000 --jsonl /tmp/theory_arms/A_s13.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s13.out 2>&1
./target/release/examples/trophic_run --seed 13 --ticks 50000 --jsonl /tmp/theory_arms/F_s13.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s13.out 2>&1
./target/release/examples/trophic_run --seed 13 --ticks 50000 --jsonl /tmp/theory_arms/AF_s13.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s13.out 2>&1
./target/release/examples/trophic_run --seed 14 --ticks 50000 --jsonl /tmp/theory_arms/A_s14.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s14.out 2>&1
./target/release/examples/trophic_run --seed 14 --ticks 50000 --jsonl /tmp/theory_arms/F_s14.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s14.out 2>&1
./target/release/examples/trophic_run --seed 14 --ticks 50000 --jsonl /tmp/theory_arms/AF_s14.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s14.out 2>&1
./target/release/examples/trophic_run --seed 15 --ticks 50000 --jsonl /tmp/theory_arms/A_s15.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s15.out 2>&1
./target/release/examples/trophic_run --seed 15 --ticks 50000 --jsonl /tmp/theory_arms/F_s15.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s15.out 2>&1
./target/release/examples/trophic_run --seed 15 --ticks 50000 --jsonl /tmp/theory_arms/AF_s15.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s15.out 2>&1
./target/release/examples/trophic_run --seed 16 --ticks 50000 --jsonl /tmp/theory_arms/A_s16.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s16.out 2>&1
./target/release/examples/trophic_run --seed 16 --ticks 50000 --jsonl /tmp/theory_arms/F_s16.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s16.out 2>&1
./target/release/examples/trophic_run --seed 16 --ticks 50000 --jsonl /tmp/theory_arms/AF_s16.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s16.out 2>&1
./target/release/examples/trophic_run --seed 17 --ticks 50000 --jsonl /tmp/theory_arms/A_s17.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s17.out 2>&1
./target/release/examples/trophic_run --seed 17 --ticks 50000 --jsonl /tmp/theory_arms/F_s17.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s17.out 2>&1
./target/release/examples/trophic_run --seed 17 --ticks 50000 --jsonl /tmp/theory_arms/AF_s17.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s17.out 2>&1
./target/release/examples/trophic_run --seed 18 --ticks 50000 --jsonl /tmp/theory_arms/A_s18.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s18.out 2>&1
./target/release/examples/trophic_run --seed 18 --ticks 50000 --jsonl /tmp/theory_arms/F_s18.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s18.out 2>&1
./target/release/examples/trophic_run --seed 18 --ticks 50000 --jsonl /tmp/theory_arms/AF_s18.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s18.out 2>&1
./target/release/examples/trophic_run --seed 19 --ticks 50000 --jsonl /tmp/theory_arms/A_s19.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true > /tmp/theory_arms/A_s19.out 2>&1
./target/release/examples/trophic_run --seed 19 --ticks 50000 --jsonl /tmp/theory_arms/F_s19.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set sig_divisor_micros=3000 --set hop_loss_milli=50 --set evidence_window=2000 > /tmp/theory_arms/F_s19.out 2>&1
./target/release/examples/trophic_run --seed 19 --ticks 50000 --jsonl /tmp/theory_arms/AF_s19.jsonl --set station_gossip_slots=16 --set craft_gossip_slots=8 --set staleness_from_rob_tick=true --set sig_divisor_micros=3000 --set hop_loss_milli=50 > /tmp/theory_arms/AF_s19.out 2>&1
